config/routes.rb
Tweet::Application.routes.draw do
  match '/auth/:provider/callback' => 'login#create' ,via: [:get, :post]
  match "/signout" => "login#signout",via: [:get, :post]
  match "/tweet" => "login#tweet" ,via: [:get, :post]
  root 'login#index'
end

app/models/city.rb
require "constants"
class City < ActiveRecord::Base
	def self.import
		file_name="#{Rails.root}/public/cities-timezone-csv.csv"
		CSV.foreach(file_name, headers: true) do |row|
	    	create! row.to_hash
    	end
	end
	def self.update_time_diff
		cities=City.all 
		cities.each do |city|
			gmt=city.GMT_Formula
			a=gmt.split("")
			if a.length > 3
				time=a[4].to_f*10+a[5].to_f+((a[7].to_f*10+a[8].to_f)/60).to_f
				time=time * (-1) if a[3]=='-'
			else
				time=0
			end
			city.time_diff=time.to_f
			city.save
		end
	end
	def getMapUrl
		zoom='15'
		size='400x400'
		map_type='roadmap'
		marker_color='red'
		marker_size='small'
		marker_label='A'
		map_url="http://maps.googleapis.com/maps/api/staticmap?zoom=#{zoom}&size=#{size}&maptype=#{map_type}&markers=color:#{marker_color}|size:#{marker_size}|label:#{marker_label}|#{lat},#{long}"
	end
	def getImageUrl
		search_string="#{name} country beautiful".gsub(" ","%20")
	  	url="http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=#{search_string}"
	  	#p url
	  	r=RestClient.get url, :content_type => :json, :accept => :json
	  	json_resp=ActiveSupport::JSON.decode r
	  	resp=json_resp["responseData"]
		result=resp["results"]
		image_url=result.first["url"]
	end
	def short_url(long_url)
		response=RestClient.post "https://www.googleapis.com/urlshortener/v1/url", { 'longUrl' => long_url, 'key' => GOOGLE_API_KEY }.to_json, :content_type => :json, :accept => :json
		short_url_response=ActiveSupport::JSON.decode response
		short_url=short_url_response["id"]
	end
	def status
		long_url=getMapUrl
		url=short_url(long_url)
		#image_url=getImageUrl
		#Good morning, CITYNAME. GMAPS_URL.
		msg="Good morning, #{name} . #{url}"
	end
end

app/models/user.rb
require 'twitter'
require 'open-uri'
class User < ActiveRecord::Base
	def self.create_twitter_user(auth)
		create! do |user|
		  	user.oauth_token=auth['credentials']['token']
		  	user.oauth_secret=auth['credentials']['secret']
		  	user.nickname=auth["info"]["nickname"]
		  	user.login=auth["info"]["name"]
		    user.provider = auth["provider"]
		    user.uid = auth["uid"]
		    user.name = auth["info"]["name"]
		end
	end
	def self.getRandomCity
		ids = City.pluck(:id).shuffle[0..0]
		city=City.find(ids.first)
	end
	def post_tweet
		city=User.getRandomCity
		client = Twitter::REST::Client.new do |config|
	    	config.consumer_key        = TWITTER_APP_ID
	      	config.consumer_secret     = TWITTER_SECRET
	      	config.access_token        = oauth_token
	      	config.access_token_secret = oauth_secret
    	end
	    uri = URI.parse(city.getImageUrl)
	    media = uri.open
	    media.instance_eval("def original_filename; '#{File.basename(uri.path)}'; end")
	    #p client.update(Time.now.to_s)
	    client.update_with_media(city.status, media)
	end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # specify configuration here, such as:
  # logout_on_timeout true
  # ...many more options in the documentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
  	helper_method :current_user

	private
  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  	
  end
  def create
  	auth=request.env['omniauth.auth']	
 	 	#@envmnt={:token=>auth['credentials']['token'],:secret=>auth['credentials']['secret'],:provider=>auth.provider,:uid=>auth.uid,:name=>auth["info"]["name"],:nick_name=>auth["info"]["nickname"]}
 	user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_twitter_user(auth)
  	session[:user_id] = user.id
  	redirect_to root_url, :notice => "Signed in!"
  end
  def signout
  	session[:user_id] = nil
	redirect_to root_url, :notice => "Signed out!"
  end
  def tweet
    if current_user
      #Resque.enqueue(TweetWorker,current_user.id) 
      post =current_user.post_tweet
      if post.created?
        message="Your <strong> #{post.full_text} </strong> has been posted  at <strong>#{post.created_at}</strong>.."
      else
        message="Your tweet has not been posted  .."
      end
    else
      message="Please login to continue.."
    end
    flash[:message]=message
    redirect_to (:back)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tweet</title>
    <%= stylesheet_link_tag   "sb-admin-2.css", "bootstrap.min.css","application", media: "all", "data-turbolinks-track" => true %>
    <link href="/assets/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/assets/plugins/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <%= javascript_include_tag "application","jquery-1.7.1.min.js","jquery.selection.js","sb-admin-2.js","bootstrap.min.js", "data-turbolinks-track" => true %> 
  	
    <script src="/assets/plugins/metisMenu/metisMenu.min.js"></script>
	<script src="/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<img class="img-responsive" src="/assets/logo.png" alt="">
            </div>

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
	<h1 class="page-header">Tweet</h1>
	<div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <% if current_user %>
 		 			Welcome <%= current_user.name %>!
                    <%= link_to "Sign Out", signout_path,  :style=>"float:right" %>
 		 	    <% end %>		
            </div>
            <div class="panel-body">
                <%= yield %>
           		<div class="alert alert-danger">
           			<% if current_user %>
						<a href="/tweet" > Click here to tweet </a>
					<% else %>
	  					<%= link_to "Sign in with Twitter", "/auth/twitter" %>
					<% end %>
                </div>
            </div>
        </div>
    </div>   
</div>
</body>
</html>

app/views/login/index.html.erb
<div class="panel-body">
	<div id="flash">
	  <% flash.each do |key, value| -%>
	      <div id="flash_<%= key %>" class="<%= key %>"><p style="color:green; font-size: 17px;"><%=raw value %></p></div>  
	  <% end %>
	</div>
</div>